### ISSUE TITLE
Segfault when shutting down openresty

### ISSUE THREAD

**Issue by terrynsun** [opentracing/lua-bridge-tracer#6]
I'm using:
* Debian stretch
* openresty 1.13.6.2
* nginx-opentracing 0.8.0
* lua-bridge-tracer 0.1.0 or master

I added the nginx-opentracing module to openresty and installed lua-bridge-tracer. I'm able to report spans from within Lua, but when shutting down openresty (by sending SIGTERM), I hit a segfault.

The backtrace looks like this:

```
$ gdb $(which openresty) core
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/openresty/bin/openresty...done.

warning: core file may not match specified executable file.
[New LWP 12491]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process                                                  '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5b16d0765a in std::_Sp_counted_ptr<opentracing::v2::Span*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x55ac4223c7d0)
    at /usr/include/c++/6/bits/shared_ptr_base.h:372
372           { delete _M_ptr; }
(gdb) bt
#0  0x00007f5b16d0765a in std::_Sp_counted_ptr<opentracing::v2::Span*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x55ac4223c7d0)
    at /usr/include/c++/6/bits/shared_ptr_base.h:372
#1  0x000055ac401aebb2 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x55ac4223c7d0)
    at /usr/include/c++/6/bits/shared_ptr_base.h:150
#2  0x00007f5b16d00b8f in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x55ac421e3b08, __in_chrg=<optimized out>)
    at /usr/include/c++/6/bits/shared_ptr_base.h:662
#3  0x00007f5b16d038e6 in std::__shared_ptr<opentracing::v2::Span, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x55ac421e3b00,
    __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr_base.h:928
#4  0x00007f5b16d03928 in std::shared_ptr<opentracing::v2::Span>::~shared_ptr (this=0x55ac421e3b00, __in_chrg=<optimized out>)
    at /usr/include/c++/6/bits/shared_ptr.h:93
#5  0x00007f5b16d0641a in lua_bridge_tracer::LuaSpan::~LuaSpan (this=0x55ac421e3af0, __in_chrg=<optimized out>)
    at /cfsetup_build/lua-bridge-tracer/src/lua_span.h:10
#6  0x00007f5b16d08060 in lua_bridge_tracer::LuaSpan::free (L=0x41f64378) at /cfsetup_build/lua-bridge-tracer/src/lua_span.cpp:38
#7  0x00007f5b5975500a in lj_BC_FUNCC () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#8  0x00007f5b59757128 in gc_call_finalizer (g=g@entry=0x41f643b8, L=L@entry=0x41f64378, mo=<optimized out>, o=o@entry=0x41f779a8) at lj_gc.c:475
#9  0x00007f5b597571e6 in gc_finalize (L=L@entry=0x41f64378) at lj_gc.c:521
#10 0x00007f5b59758108 in lj_gc_finalize_udata (L=L@entry=0x41f64378) at lj_gc.c:528
#11 0x00007f5b5975e481 in cpfinalize (L=0x41f64378, dummy=<optimized out>, ud=<optimized out>) at lj_state.c:236
#12 0x00007f5b59755379 in lj_vm_cpcall () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
#13 0x00007f5b5975e796 in lua_close (L=0x41f64378) at lj_state.c:262
#14 0x000055ac401560dc in ngx_http_lua_cleanup_vm (data=0x55ac422202b0) at ../ngx_lua-0.10.13/src/ngx_http_lua_util.c:3827
#15 0x000055ac400a2516 in ngx_destroy_pool (pool=0x55ac421d55d0) at src/core/ngx_palloc.c:60
#16 0x000055ac400c5e23 in ngx_worker_process_exit (cycle=cycle@entry=0x55ac421d5620) at src/os/unix/ngx_process_cycle.c:1071
#17 0x000055ac400c5fa7 in ngx_worker_process_cycle (cycle=cycle@entry=0x55ac421d5620, data=data@entry=0x0) at src/os/unix/ngx_process_cycle.c:814
#18 0x000055ac400c48ec in ngx_spawn_process (cycle=cycle@entry=0x55ac421d5620, proc=proc@entry=0x55ac400c5e80 <ngx_worker_process_cycle>,
    data=data@entry=0x0, name=name@entry=0x55ac401b8d3d "worker process", respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:198
#19 0x000055ac400c63a0 in ngx_start_worker_processes (cycle=cycle@entry=0x55ac421d5620, n=1, type=type@entry=-3)
    at src/os/unix/ngx_process_cycle.c:396
#20 0x000055ac400c6d2a in ngx_master_process_cycle (cycle=0x55ac421d5620) at src/os/unix/ngx_process_cycle.c:135
#21 0x000055ac4009fcdd in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:384
(gdb)
```

**Comment by rnburn** [comment]
Could you check to see if this [commit](https://github.com/opentracing/lua-bridge-tracer/commit/696c6f34acc25d5caf6d0b6eac33b978f04b0909) fixes the problem?

**Comment by terrynsun** [comment]
That commit doesn't fix the problem for me.

**Comment by terrynsun** [comment]
Here's the config I'm running OpenResty with - does anything stand out?

```
worker_processes        1;
error_log               /dev/stdout;
pid                     run/nginx.pid;

events {
    worker_connections  16;
    accept_mutex        off;
    multi_accept        off;
    use                 epoll;
}

http {
    opentracing on;
    opentracing_load_tracer /usr/local/lib/libjaegertracing_plugin.so jaeger-config.yml;

    opentracing_trust_incoming_span off;
    log_subrequest on;

    access_log          /dev/stdout;

    server {
        server_name 'proxy';
        listen 8004;

        location / {
            content_by_lua '
                local bridge_tracer = require("opentracing_bridge_tracer")
                local tracer = bridge_tracer.new_from_global()
                local parent_context = tracer:binary_extract(ngx.var.opentracing_binary_context)
                local span = tracer:start_span("lua-hello", {["references"] = {{"child_of", parent_context}}})
                ngx.say("<p>hello, world</p>")
                span:finish()
            ';
        }
    }
}
```

**Comment by rnburn** [comment]
I think I found the issue. Could you check to see if [this PR](https://github.com/opentracing-contrib/nginx-opentracing/pull/97) solves the problem?

**Comment by terrynsun** [comment]
That fixes it for me. Thanks!
